server:
  port: 8080

spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: favorite
            uri: http://k8s-favorite-service:8080
            predicates:
              - Path=/api/favorite/v1/**

          - id: interest
            uri: http://k8s-interest-service:8080
            predicates:
              - Path=/api/interests/v1/**